In [1]:
'''1. You are given a N X M integer array matrix with space separated elements (N = rows and M = columns).
Your task is to print the transpose and flatten results.'''

import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [2]:
'''2. You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.'''

import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    arr = numpy.array(arr,dtype=float)
    return arr

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5
[5. 4. 3. 2. 1.]


In [4]:
'''3. You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.'''

import numpy
arr = input().strip().split(' ')
arr = numpy.array(arr,dtype=int)
arr.shape = (3,3)
print(arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
'''4. The first line contains space separated integers N, M and P.
The next N lines contains the space separated elements of the P columns.
After that, the next M lines contains the space separated elements of the P columns.'''

import numpy

n, m, p = map(int, input().split())
arraynp = numpy.array([input().strip().split() for _ in range(n)], int)
arraymp = numpy.array([input().strip().split() for _ in range(m)], int)

print(numpy.concatenate((arraynp,arraymp),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [8]:
'''5. You are given the shape of the array in the form of space-separated integers, each integer representing the size of 
different dimensions, your task is to print an array of the given shape and integer type using the tools 
numpy.zeros and numpy.ones.'''

import numpy
nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [9]:
'''6. Your task is to print an array of size N X M with its main diagonal elements as 1's and 0's everywhere else.'''
import numpy

N,M = list(int(x) for x in input().split())

print(numpy.eye(N,M))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
'''7. You are given two integer arrays, A and B of dimensions N X M.
Your task is to perform the following operations:

Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )'''

import numpy
n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
B=numpy.array([list(map(int,input().split())) for i in range(n)])
print(A+B,A-B,A*B,A//B,A%B,A**B,sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [11]:
'''8. You are given a 2-D array with dimensions N X M.
Your task is to perform the sum tool over axis 0 and then find the product of that result.'''

import numpy
n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
print(numpy.prod(numpy.sum(A, axis=0)))

2 2
1 2
3 4
24


In [12]:
'''9. You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A.'''

import numpy
numpy.set_printoptions(legacy='1.13')
A = list(float(x) for x in input().split())
A = numpy.array(A)
print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [13]:
'''10. You are given a 2-D array with dimensions N X M.
Your task is to perform the min function over axis 1 and then find the max of that.'''

import numpy

n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
print(numpy.max(numpy.min(A,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


In [14]:
'''11.You are given a 2-D array of size N X M.
Your task is to find:

The mean along axis 1
The var along axis 0
The std along axis None'''

import numpy as np
n, m = map(int, input().split())
k = np.array([input().split() for _ in range(n)],dtype = int)

print(np.mean(k,axis=1), np.var(k,axis=0), round(np.std(k),11), sep='\n')

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [15]:
'''12. You are given two arrays A and B. Both have dimensions of N X N.
Your task is to compute their matrix product.'''

import numpy
n = int(input())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
B=numpy.array([list(map(int,input().split())) for i in range(n)])

print(numpy.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [16]:
'''13. You are given two arrays: A and B.
Your task is to compute their inner and outer product.'''

import numpy

A = numpy.array(list(int(x) for x in input().split()))
B = numpy.array(list(int(x) for x in input().split()))
print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


In [17]:
'''14. You are given the coefficients of a polynomial P.
Your task is to find the value of P at point x.'''

import numpy
print(numpy.polyval(numpy.array(input().split(),float),int(input())))


1.1 2 3
0
3.0


In [18]:
'''15. You are given a square matrix A with dimensions N X N. Your task is to find the determinant. 
Note: Round the answer to 2 places after the decimal.'''

import numpy
array=[list(map(float,input().split())) for i in range(int(input()))]
print(round(numpy.linalg.det(array),2))

2
1.1 1.1
1.1 1.1
0.0
